---
apiVersion: v1
kind: Service
metadata:
  name: remix-app-service
spec:
  selector:
    app: remix-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
#  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix-app
  labels:
    app: remix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remix-app
  template:
    metadata:
      labels:
        app: remix-app
    spec:
      containers:
      - name: remix-app
        image: registry.local:5000/remix-app:latest
        ports:
        - containerPort: 3000
        env:
        - {name: NODE_ENV, value: "production"}

